# This is a basic workflow to help you get started with Actions

name: DOCS

# Controls when the workflow will run
on:
  push:
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Generate docs
        run: |
          pip install -r requirements.txt
          cd docs
          pip install -r requirements.txt
          make clean ; make html
          
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TOKEN }}
        with:
          source-directory: 'docs/build/html'
          destination-github-username: 'sys-eng-team14'
          destination-repository-name: 'sys-eng-team14.github.io'
          user-email: bozzhanov.at@gmail.com
          target-branch: main
